version: "3.8"

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - .:/workspace/.devcontainer
      - workspace:/workspace
      - nodemodules:/workspace/node_modules:cached
      - ../playwright-report:/workspace/playwright-report
      - ../.gitconfig:/workspace/.gitconfig

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  workspace: null
  nodemodules: null
