name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ci
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: yarn
      - run: yarn lint --if-present
      - run: yarn prettier:check --if-present
      - run: yarn test
      - run: yarn build --if-present
